In [2]:
import numpy as np
array = np.arange(2,51,3)
print(array)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [4]:
import numpy as np
a1=[] 
a2=[]
for i in range(0, 5): 
    ele = int(input())
    a1.append(ele)
for i in range(0, 5): 
    ele = int(input())
    a2.append(ele) 
a1 = np.array(a1)
a2 = np.array(a2)
print(np.concatenate((a1,a2)))
print(np.sort(np.concatenate((a1,a2))))


2
3
4
5
6
7
8
12
3
45
[ 2  3  4  5  6  7  8 12  3 45]
[ 2  3  3  4  5  6  7  8 12 45]


In [8]:
import numpy as np
arr = np.array([[1,3,5],[1,3,4],[2,3,5]])
print(arr.ndim)
print(arr.size)

2
9


In [9]:
import numpy as np
arr=np.random.rand(5,)
print(arr.ndim)
nw_arr = arr[np.newaxis, :]
print(nw_arr.ndim)

1
2


In [10]:
import numpy as np
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
print(np.vstack((arr1,arr2)))
print() 
print(np.hstack((arr1,arr2)))

[[0.86726827 0.26020939 0.46472979]
 [0.11199391 0.77654679 0.13266903]
 [0.06461555 0.09196926 0.32372308]
 [0.62237277 0.94358735 0.03590747]
 [0.67607272 0.81439335 0.09076935]
 [0.71627137 0.74676217 0.46575283]]

[[0.86726827 0.26020939 0.46472979 0.62237277 0.94358735 0.03590747]
 [0.11199391 0.77654679 0.13266903 0.67607272 0.81439335 0.09076935]
 [0.06461555 0.09196926 0.32372308 0.71627137 0.74676217 0.46575283]]


In [13]:
import numpy as np
arr = np.array([1,2,3,45,6,7,89,67,2,3,22,2,2,3])
print(np.unique(arr,return_counts=True))

(array([ 1,  2,  3,  6,  7, 22, 45, 67, 89]), array([1, 4, 3, 1, 1, 1, 1, 1, 1], dtype=int64))
